tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: main_logo
            field:
              container: assets
              type: assets
              display: 'Main Logo'
              max_files: 1
              min_files: 1
