title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: services_short_content
            field:
              type: textarea
              display: 'Services Short Content'
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: services_thumbnail_image
            field:
              container: assets
              type: assets
              display: 'Services Thumbnail Image'
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
