title: External
content: 'This is Content'
author: ce4d9da0-2744-4453-a6cd-e1ca8d18260e
updated_by: ce4d9da0-2744-4453-a6cd-e1ca8d18260e
updated_at: 1756195458
thumbnail_image: tengyart-ksvptrfhaiu-unsplash.jpg
blueprint: product_type
